{
 "title": "Discord Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_dm = '0'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Total Commands",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Successful Commands",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  success = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "User Commands",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '.'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Total Discord Event Counts",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  event AS metric,\n  count\nFROM statistics\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Challenge Commands",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '&'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "DM Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_dm = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  success = '0'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Admin Commands",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '~'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Status Changes Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(member_id) AS \"member_id\"\nFROM member_status_logs\nWHERE\n  $__timeFilter(created_at) AND\n  status = 'online'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(member_id) AS \"member_id\"\nFROM member_status_logs\nWHERE\n  $__timeFilter(created_at) AND\n  status = 'idle'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(member_id) AS \"member_id\"\nFROM member_status_logs\nWHERE\n  $__timeFilter(created_at) AND\n  status = 'offline'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(member_id) AS \"member_id\"\nFROM member_status_logs\nWHERE\n  $__timeFilter(created_at) AND\n  status = 'dnd'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id) AS \"user_id\"\nFROM members"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id) AS \"user_id\"\nFROM members\nWHERE \n  status = 'online'"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id) AS \"user_id\"\nFROM members\nWHERE \n  status = 'idle'"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id) AS \"user_id\"\nFROM members\nWHERE \n  status = 'offline'"
    }
   ]
  },
  {
   "title": "DND",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(user_id) AS \"user_id\"\nFROM members\nWHERE \n  status = 'dnd'"
    }
   ]
  },
  {
   "title": "Messages per Minute (messages the bot can see)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(channel_id) AS \"total_msgs\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(channel_id) AS \"dm_count\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_dm = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1m,0),\n  count(channel_id) AS \"channel_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_dm = '0'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1m,0)"
    }
   ]
  },
  {
   "title": "Bot commands per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '.'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '&'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM command_logs\nWHERE\n  $__timeFilter(created_at) AND\n  prefix = '~'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Top Talkers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  user_name AS metric,\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1,2\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Messages Edited / Deleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_deleted = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM message_logs\nWHERE\n  $__timeFilter(created_at) AND\n  is_edited = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  },
  {
   "title": "Flag Submissions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM flag_logs\nWHERE\n  $__timeFilter(created_at) AND\n  success = '1'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval,0),\n  count(message_id) AS \"message_id\"\nFROM flag_logs\nWHERE\n  $__timeFilter(created_at) AND\n  success = '0'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval,0)"
    }
   ]
  }
 ]
}